#!/usr/bin/env bash
# design-md.sh — generates and verifies DESIGN.md from design/tokens.css.
#
# DESIGN.md is the draft specification Google Labs released in April 2026
# (google-labs-code/design.md, Apache 2.0): a file at the root that gives any AI
# agent the design system in a format it understands, the same way AGENTS.md does
# for the repository instructions.
#
# WHY IT IS GENERATED AND NOT WRITTEN:
#   The spec asks for the tokens in the YAML frontmatter. But the tokens already live
#   in design/tokens.css, which is what the browser reads at runtime and what your UI
#   framework consumes. Writing DESIGN.md by hand would be a SECOND COPY of the same
#   values — exactly the drift this repository avoids everywhere else (that is why
#   design/preview.html links tokens.css instead of copying it).
#   So tokens.css rules and DESIGN.md is derived. If they diverge, the CSS wins.
#
# Usage:
#   bash .github/scripts/design-md.sh --write   # regenerate DESIGN.md
#   bash .github/scripts/design-md.sh           # verify it is in sync (CI)
#
# Requires: python3. Exits 1 if DESIGN.md does not match tokens.css.
set -euo pipefail

ROOT="${2:-.}"
[ "${1:-}" = "--write" ] || ROOT="${1:-.}"
cd "$ROOT"

TOKENS="design/tokens.css"
OUT="DESIGN.md"

# Without design/ there is no design system to document: it is a product with no
# interface and DESIGN.md does not apply. An orphan one would be worse than none.
if [ ! -f "$TOKENS" ]; then
  if [ -f "$OUT" ]; then
    echo "❌ There is $OUT but no $TOKENS: either the source is missing, or the generated file is left over."
    echo "→ If the product has no interface, delete $OUT."
    exit 1
  fi
  echo "ℹ️  No $TOKENS: the product has no design system. Nothing to generate."
  exit 0
fi

generated="$(python3 - "$TOKENS" <<'PY'
import re, sys

css = open(sys.argv[1], encoding="utf-8").read()
css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)  # drop comments


def blocks(pattern):
    """Merges ALL matching blocks: tokens.css has more than one `:root`
    —color in one, geometry and typography in another— and keeping only the
    first silenced half the typography."""
    vals = {}
    for m in re.finditer(pattern + r"\s*\{(.*?)\n\}", css, re.S):
        vals.update(re.findall(r"--([a-z0-9-]+)\s*:\s*([^;]+);", m.group(1)))
    return vals


light = blocks(r":root(?!\[)(?!:)")
dark = blocks(r":root\[data-theme=\"dark\"\]")

def yaml(v):
    """Single-quoted YAML scalar: typography values carry double quotes inside
    ("Inter", "Space Grotesk") and quoting them with doubles produced invalid
    YAML that no agent could parse."""
    return "'" + " ".join(v.split()).replace("'", "''") + "'"


# Order matters: it is the reading order, not the alphabetical one.
order = [
    "base-100", "base-200", "base-300", "base-content",
    "primary", "primary-content", "secondary", "secondary-content",
    "accent", "accent-content", "neutral", "neutral-content",
    "info", "info-content", "success", "success-content",
    "warning", "warning-content", "error", "error-content",
]

out = ["---", "# GENERATED by .github/scripts/design-md.sh — do not edit by hand.",
       "# The source of truth is design/tokens.css.", "colors:"]
for theme, vals in (("light", light), ("dark", dark)):
    if not vals:
        continue
    out.append(f"  {theme}:")
    for k in order:
        if k in vals:
            out.append(f"    {k}: {yaml(vals[k])}")

typo = {k: v for k, v in light.items() if k in ("sans", "display", "mono")}
if typo:
    out.append("typography:")
    for k, v in typo.items():
        out.append(f"  {k}: {yaml(v)}")

radii = {k: v for k, v in light.items() if k in ("field", "box")}
if radii:
    out.append("radius:")
    for k, v in radii.items():
        out.append(f"  {k}: {yaml(v)}")

out += [
    "---",
    "",
    "# Design system",
    "",
    "The tokens above are the product's full palette, in OKLCH and in both themes.",
    "**Always use them by name** (`var(--primary)`, or your framework's equivalent",
    "utility): never write a hex or a raw palette utility in a component.",
    "",
    "This file is generated by `.github/scripts/design-md.sh` from `design/tokens.css`,",
    "which is the source of truth — the browser reads it at runtime and your UI framework",
    "consumes it through the adapter at the end. Editing it by hand achieves nothing: CI",
    "compares the two and fails.",
    "",
    "## Where the rest lives",
    "",
    "- **The rules** —native primitives before custom components, the four states of every",
    "  view, AA accessibility in both themes— in [`docs/conventions/ui.md`](docs/conventions/ui.md).",
    "- **Seeing it applied**: open [`design/preview.html`](design/preview.html) in the browser.",
    "  It links `tokens.css` directly and computes contrast live, so it shows the real",
    "  colors and not a description of them.",
    "- **Choosing a new product's palette**: the `/identity` skill.",
    "",
]
print("\n".join(out))
PY
)"

if [ "${1:-}" = "--write" ]; then
  printf '%s\n' "$generated" >"$OUT"
  echo "✅ $OUT regenerated from $TOKENS."
  exit 0
fi

if [ ! -f "$OUT" ]; then
  echo "❌ $OUT is missing. Generate it with: bash .github/scripts/design-md.sh --write"
  exit 1
fi

if ! printf '%s\n' "$generated" | diff -q - "$OUT" >/dev/null; then
  echo "❌ $OUT does not match $TOKENS."
  echo "→ The tokens rule. Regenerate with: bash .github/scripts/design-md.sh --write"
  exit 1
fi
echo "✅ DESIGN.md in sync with design/tokens.css."
