blank_issues_enabled: false
contact_links:
  - name: Project Documentation
    url: "[REPOSITORY_URL]/wiki"
    about: Check the full project documentation
  - name: Community Discussions
    url: "[REPOSITORY_URL]/discussions"
    about: Join the discussions to ask general questions
